#!/bin/bash

FIRMWARES="
EMUPS4
EMU360
EMUPS3
EMUXBOX
joystick-serial"

TARGETS="
atmega32u4
atmega32u2
atmega16u4
at90usb1287
at90usb1286
at90usb647
at90usb646
at90usb162"

mkdir firmwares

for FIRMWARE in $FIRMWARES
do
  mkdir firmwares/$FIRMWARE
  cd $FIRMWARE
  make clean
  for TARGET in $TARGETS
  do
    make MCU=$TARGET
    mv *.hex ../firmwares/$FIRMWARE/$TARGET.hex
    make clean
  done
  cd ..
done

zip -r firmwares.zip firmwares
