#!/bin/bash

FIRMWARES="
EMUPS4
EMU360
EMUPS3
EMUXBOX
EMUJOYSTICKPS3
EMUT300RSPS4
EMUG27PS3
EMUG29PS4
EMUXONE"

TARGETS="
atmega32u4
atmega32u2
atmega16u4
at90usb1287
at90usb1286
at90usb647
at90usb646
at90usb162"

VERSION=`cat version`

echo "Version number? (default: "$VERSION")"

read NEW_VERSION

if [ -z $NEW_VERSION ]
then
  NEW_VERSION=$VERSION
fi

if [ -z $NEW_VERSION ]
then
  echo No version specified!
  exit
fi

echo $NEW_VERSION > version

DIR="firmwares-$NEW_VERSION"

rm -rf $DIR $DIR.zip

mkdir $DIR

for FIRMWARE in $FIRMWARES
do
  echo Making $FIRMWARE:
  mkdir $DIR/$FIRMWARE
  cd $FIRMWARE
  make clean > /dev/null
  for TARGET in $TARGETS
  do
    echo "* $TARGET"
    make MCU=$TARGET > /dev/null
    mv *.hex ../$DIR/$FIRMWARE/$TARGET.hex
    make clean > /dev/null
  done
  cd ..
done

zip -r $DIR.zip $DIR
