#!/bin/bash

FIRMWARES="
EMUJOYSTICK
EMU360
EMUPS3
EMUXBOX
EMUPS4
EMUXONE
EMUG27
EMUG29PS4
EMUDF
EMUDFP
EMUGTF"

TARGETS="
atmega32u4"

VERSION=`cat version`

echo "Version number? (default: "$VERSION")"

read NEW_VERSION

if [ -z $NEW_VERSION ]
then
  NEW_VERSION=$VERSION
fi

if [ -z $NEW_VERSION ]
then
  echo No version specified!
  exit
fi

echo $NEW_VERSION > version

DIR="firmwares-$NEW_VERSION"

rm -rf $DIR $DIR.zip

mkdir $DIR

for FIRMWARE in $FIRMWARES
do
  echo Making $FIRMWARE:
  mkdir $DIR/$FIRMWARE
  cd $FIRMWARE
  make clean > /dev/null
  for TARGET in $TARGETS
  do
    echo "* $TARGET"
    make MCU=$TARGET > /dev/null
    mv *.hex ../$DIR/$FIRMWARE/$TARGET.hex
    make clean > /dev/null
  done
  cd ..
done

zip -r $DIR.zip $DIR
