#ifndef _ADAPTER_CONFIG_H_
#define _ADAPTER_CONFIG_H_

#define ADAPTER_TYPE         BYTE_TYPE_G920_XONE
#define ADAPTER_IN_NUM       (ENDPOINT_DIR_IN | 1)
#define ADAPTER_IN_SIZE      64
#define ADAPTER_IN_INTERVAL  4
#define ADAPTER_OUT_NUM      (ENDPOINT_DIR_OUT | 2)
#define ADAPTER_OUT_SIZE     64
#define ADAPTER_OUT_INTERVAL 4

#endif
