#!/bin/bash

TARGETS="
atmega32u4
atmega32u2
atmega16u4
at90usb1287
at90usb1286
at90usb647
at90usb646
at90usb162"

mkdir firmwares

for TARGET in $TARGETS
do
  make clean
  make MCU=$TARGET
  mv X360PE.hex firmwares/$TARGET.hex
done

zip -r firmwares.zip firmwares
